### ISSUE TITLE
Does SwagGen support references to properties of a schema?

### ISSUE THREAD

**Issue by raphaeloliveira** [yonaskolb/SwagGen#166]
Hey @yonaskolb, our backend team recently added on our openapi spec the following entry on `schemas:`

A new `UpdateCardRequest`
```
    UpdateCardRequest:
      type: object
      required:
        - nickname
      properties:
        nickname:
          $ref: '#/components/schemas/Card/properties/nickname'
```

A new property called `nickname` under the existing `Card` schema.
```
    Card:
      type: object
      properties:
        ...
        nickname:  
          type: string
          nullable: true
```

When swaggen generates the code, `Card` correctly receives the new `nickname` property of type `String`. However, the new `UpdateCardRequest` object fails to compile due to unknown Nickname type. Apparently having a `$ref` to a property (`Card/properties/nickname`) does not make Swaggen generate a typealias or a new object. Is my assumption correct?

As a temporary workaround I could make Nickname a new object under `schema` and have the `nickname` property under `Card` reference it. Thoughts?
