### ISSUE TITLE
TemplateFiles - Context Options

### ISSUE THREAD

**Issue by JacobJerrell** [yonaskolb/SwagGen#169]
@yonaskolb I've been having an issue with the following line from the readme.md regarding the template.yml file;

> Note that properties in the template `options` field can be used here

The models my team uses are somewhat unique and I essentially need to generate 2 files for each schema; a resource model, and a wrapper. I need the resource models to have a suffix but not the wrappers. I'm trying to implement it like this:

```
templateFiles:
  - path: Sources/Dto.swift
    context: schemas
    modelSuffix: Dto # applied to model classes
    destination: "Sources/Dtos/{{ type }}.swift"
```

I've played with the positioning of the modelSuffix option in many different ways beneath context, but this is the only one that doesn't result in an error at runtime. But it still doesn't add a suffix to the files. I can't find any examples of options being used in templateFiles->context
