### ISSUE TITLE
Property type Decimal instead of Double

### ISSUE THREAD

**Issue by benrudhart** [yonaskolb/SwagGen#184]
My yaml defines the property of a model with type `number`.
This generates the Swift type `Double`.

I'm looking for a way to automatically generate a Swift `Decimal`. 
I thought something like this should work, but format is `ignored` in this case (generates Swift `Double`)
```
 Foo:
      properties:
        bar:
          type: number
          format: decimal
```
