### ISSUE TITLE
int64 integers are not being generated to Int64 but instead to Int

### ISSUE THREAD

**Issue by marcelvoss** [yonaskolb/SwagGen#264]
Hi there,

we have a field in our API definition that has a int64 type but after generating had to realize that SwagGen does not respect that and generates to a regular Int with precision depending on the platform's architecture. In our case, this might actually make us lose precision. 

Example from our spec:
```
legacy_id:
          deprecated: true
          type: integer
          format: int64
          example: 100067734
```
